version: '3.4'
services:
    db:
      image: postgres
      ports:
        - "6543:5432"
      networks:
        - app-net
      expose:
        - "6543"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: visitsroutes
      volumes:
        - postgres-data:/var/lib/postgresql/data
      restart: unless-stopped
    vr_back_end:
      image: vr_back_end
      depends_on:
        - db
      ports:
        - 8080:8080
      networks:
        - app-net
      build:
        context: ./back-end/
        dockerfile: Dockerfile
      restart: unless-stopped
    vr_front_end:
      image: vr_front_end
      depends_on:
        - vr_back_end
      ports:
        - 4200:80
      networks:
        - app-net
      build:
        context: ./front-end/
        dockerfile: Dockerfile
      restart: unless-stopped
volumes:
  postgres-data:        

networks:
  app-net: